name: unified_apple_vision_example
description: "Demonstrates how to use the unified_apple_vision plugin."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  camerawesome: ^2.0.0+1
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  path_provider: ^2.1.2
  unified_apple_vision:
    path: ../

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
