name: unified_apple_vision
description: "A plugin for using Apple Vision Framework with Flutter, designed to integrate multiple APIs into one plugin and process multiple analysis requests at once."
version: 1.1.0
homepage: https://github.com/ywake/unified_apple_vision

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  uuid: ^4.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: UnifiedAppleVisionPlugin
        sharedDarwinSource: true
      macos:
        pluginClass: UnifiedAppleVisionPlugin
        sharedDarwinSource: true
