name: unified_apple_vision
description: "A Flutter plugin for using apple's vision framework."
version: 0.1.0
homepage: https://github.com/ywake/unified_apple_vision

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: UnifiedAppleVisionPlugin
        sharedDarwinSource: true
      macos:
        pluginClass: UnifiedAppleVisionPlugin
        sharedDarwinSource: true
